const samples={bill:`中華電信 113年 6月電信帳單
本期應繳金額 NT$1,286
繳費期限 2026/07/05
服務項目：行動電話月租費、網路費、加值服務。
如逾期繳納，可能產生違約金或影響服務。`,insurance:`安心人壽 終身醫療保險 保單通知
保單號碼 A123456789
要保人 王小明
年繳保費 NT$24,800
下次繳費日 2026/08/15
保障內容包含住院日額、手術醫療、重大傷病附約。
請確認受益人資料與扣款帳戶是否仍有效。`,subsidy:`台北市青年租金補貼申請公告
申請期間：2026/06/20 至 2026/07/31
補助對象：設籍或就業於台北市，符合所得及租屋資格者。
應備文件：身分證明、租賃契約、所得證明、金融帳戶影本。
線上申請後需留意補件通知。`};
const categoryRules=[{category:"報稅",keywords:["報稅","所得稅","扣繳","租金","醫療支出","扶養"]},{category:"保險",keywords:["保單","保險","保費","受益人","保障","附約"]},{category:"信用卡",keywords:["信用卡","回饋","登錄","刷卡","紅利","哩程"]},{category:"訂閱",keywords:["訂閱","月費","續訂","方案","自動扣款"]},{category:"帳單",keywords:["帳單","應繳","繳費","水費","電費","電信","瓦斯"]},{category:"政府補助",keywords:["補助","申請","資格","應備文件","政府","市府"]},{category:"行程提醒",keywords:["會議","預約","行程","報到","截止"]}];
const els={fileInput:document.querySelector("#fileInput"),fileStatus:document.querySelector("#fileStatus"),documentText:document.querySelector("#documentText"),analyzeButton:document.querySelector("#analyzeButton"),resultTitle:document.querySelector("#resultTitle"),categoryOutput:document.querySelector("#categoryOutput"),issuerOutput:document.querySelector("#issuerOutput"),amountOutput:document.querySelector("#amountOutput"),dateOutput:document.querySelector("#dateOutput"),taskList:document.querySelector("#taskList"),summaryOutput:document.querySelector("#summaryOutput"),formOutput:document.querySelector("#formOutput"),traceOutput:document.querySelector("#traceOutput")};
function clean(t){return t.replace(/\s+/g," ").trim()}function html(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function detectCategory(text){const scores=categoryRules.map(rule=>({category:rule.category,score:rule.keywords.reduce((n,k)=>n+(text.includes(k)?1:0),0)})).sort((a,b)=>b.score-a.score);return scores[0].score>0?scores[0].category:"其他文件"}
function extractAmount(text){const patterns=[/(?:NT\$|NTD)\s*([0-9]{1,3}(?:,[0-9]{3})+|[0-9]{2,7})/i,/(?:新台幣|金額|保費|應繳金額|月費|費用)[:：\s]*(?:NT\$|NTD)?\s*([0-9]{1,3}(?:,[0-9]{3})+|[0-9]{2,7})\s*(?:元)?/i];for(const p of patterns){const m=text.match(p);if(m)return`NT$${m[1]}`}return"未偵測"}
function extractDate(text){const patterns=[/(\d{4}[/-]\d{1,2}[/-]\d{1,2})\s*(?:至|-|~)\s*(\d{4}[/-]\d{1,2}[/-]\d{1,2})/i,/(?:繳費期限|下次繳費日|申請期間|截止日|期限|到期日)[:：\s]*(\d{4}[/-]\d{1,2}[/-]\d{1,2})/i,/(\d{4}[/-]\d{1,2}[/-]\d{1,2})/i];for(const p of patterns){const m=text.match(p);if(m)return m[2]?`${m[1]} 至 ${m[2]}`:m[1]}return"未偵測"}
function extractIssuer(text){const first=text.split(/\n/).map(l=>l.trim()).find(Boolean);if(!first)return"未偵測";const issuers=["中華電信","台灣大哥大","遠傳","安心人壽","國泰","富邦","台北市","新北市","財政部"];return issuers.find(i=>first.includes(i)||text.includes(i))||first.slice(0,18)}
function useFor(c){return{報稅:"年度報稅資料整理與扣除額文件檢核",保險:"保單整理、繳費提醒與保障摘要",信用卡:"優惠登錄、到期日與消費條件提醒",訂閱:"週期扣款、取消期限與月費總覽",帳單:"繳費提醒、金額核對與逾期風險提示",政府補助:"資格檢查、申請期限與應備文件清單",行程提醒:"截止日、報到資訊與待辦提醒"}[c]||"個人行政文件摘要與待辦整理"}
function buildTasks(r){const tasks=[];if(r.date!=="未偵測")tasks.push({title:`建立${r.category}提醒`,detail:`在 ${r.date} 前完成確認，避免漏繳、逾期或錯過申請。`,meta:"提醒"});if(r.amount!=="未偵測")tasks.push({title:"確認金額與付款方式",detail:`本文件偵測到 ${r.amount}，請核對帳戶、信用卡或轉帳資訊。`,meta:"金額"});if(r.category==="保險")tasks.push({title:"檢查保單基本資料",detail:"確認受益人、扣款帳戶、保障內容與附約是否仍符合目前需求。",meta:"保單"});if(r.category==="政府補助")tasks.push({title:"準備申請文件",detail:"整理身分證明、資格證明、契約、所得或金融帳戶資料，並追蹤補件通知。",meta:"補助"});return tasks.length?tasks:[{title:"補充文件資訊",detail:"目前缺少明確日期、金額或行政事項。請補上完整公告、帳單明細或保單通知。",meta:"待補"}]}
function analyzeDocument(text){const c=clean(text),category=detectCategory(c),amount=extractAmount(c),date=extractDate(c),issuer=extractIssuer(text),missing=[];if(amount==="未偵測")missing.push("金額");if(date==="未偵測")missing.push("期限或日期");if(issuer==="未偵測")missing.push("機構名稱");const rule=categoryRules.find(r=>r.category===category);const evidence=rule?rule.keywords.filter(k=>c.includes(k)).slice(0,4).join("、"):"";const r={category,amount,date,issuer,missing,categoryEvidence:evidence?`命中關鍵字：${evidence}`:""};r.tasks=buildTasks(r);r.summary=[{title:"文件重點",detail:`這份資料被歸類為「${r.category}」，主要機構為「${r.issuer}」，偵測金額為「${r.amount}」。`},{title:"下一步",detail:r.date==="未偵測"?"請補充明確期限，再建立提醒。":`請在 ${r.date} 前完成核對、付款或申請動作。`},{title:"風險提醒",detail:"AI 僅做資訊整理輔助，正式申報、保險決策、補助資格與繳費結果仍需使用者自行確認。"}];if(missing.length)r.summary.push({title:"缺少資料",detail:`建議補充：${missing.join("、")}。`});r.formDraft=[["文件分類",r.category],["機構名稱",r.issuer],["金額",r.amount],["期限/日期",r.date],["建議用途",useFor(r.category)],["資料保存","不保存原始檔，僅保存使用者確認後的摘要與提醒"]];r.trace=[["分類依據",r.categoryEvidence||"依文件關鍵字與語意判斷"],["金額來源",r.amount==="未偵測"?"未在內容中找到明確金額":`擷取到金額片段：${r.amount}`],["日期來源",r.date==="未偵測"?"未在內容中找到明確日期":`擷取到日期片段：${r.date}`],["原檔狀態","Demo 版不保存原始檔，也不提供下載或再次開啟"]];return r}
function render(r){els.resultTitle.textContent=`${r.category}整理結果`;els.categoryOutput.textContent=r.category;els.issuerOutput.textContent=r.issuer;els.amountOutput.textContent=r.amount;els.dateOutput.textContent=r.date;els.taskList.innerHTML=r.tasks.map(t=>`<article class="task-card"><div><h4>${html(t.title)}</h4><p>${html(t.detail)}</p></div><span class="task-meta">${html(t.meta)}</span></article>`).join("");els.summaryOutput.innerHTML=r.summary.map(i=>`<article class="summary-item"><h4>${html(i.title)}</h4><p>${html(i.detail)}</p></article>`).join("");els.formOutput.innerHTML=r.formDraft.map(([l,v])=>`<div class="draft-row"><strong>${html(l)}</strong><p>${html(v)}</p></div>`).join("");els.traceOutput.innerHTML=r.trace.map(([l,v])=>`<article class="trace-item"><h4>${html(l)}</h4><p>${html(v)}</p></article>`).join("")}
function empty(message){els.resultTitle.textContent="需要更多資料";els.categoryOutput.textContent="未完成";els.issuerOutput.textContent="未偵測";els.amountOutput.textContent="未偵測";els.dateOutput.textContent="未偵測";els.taskList.innerHTML=`<article class="task-card"><div><h4>請補充文件內容</h4><p>${html(message)}</p></div><span class="task-meta">待補</span></article>`;els.summaryOutput.innerHTML="";els.formOutput.innerHTML="";els.traceOutput.innerHTML=""}
document.querySelectorAll(".sample-button").forEach(b=>b.addEventListener("click",()=>{els.documentText.value=samples[b.dataset.sample]||"";els.documentText.focus()}));els.analyzeButton.addEventListener("click",()=>{const text=els.documentText.value.trim();text.length<12?empty("請貼上完整帳單、保單、補助公告或行政通知文字，再執行 AI 整理。") : render(analyzeDocument(text))});els.fileInput.addEventListener("change",e=>{const f=e.target.files?.[0];els.fileStatus.textContent=f?`已選擇：${f.name}。Demo 版不保存原始檔，請貼上文字內容進行解析。`:"尚未選擇檔案"});document.querySelectorAll(".tab").forEach(tab=>tab.addEventListener("click",()=>{const target=tab.dataset.tab;document.querySelectorAll(".tab").forEach(item=>{item.classList.toggle("active",item===tab);item.setAttribute("aria-selected",item===tab?"true":"false")});document.querySelectorAll(".tab-panel").forEach(panel=>{const active=panel.id===`${target}Panel`;panel.classList.toggle("active",active);panel.hidden=!active})}));els.documentText.value=samples.bill;render(analyzeDocument(samples.bill));
